//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARPAVTemporali.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ARPAVTemporali.Localization.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string OperazioneCompletata {
            get {
                return ResourceManager.GetString("OperazioneCompletata", resourceCulture);
            }
        }
        
        internal static string ImmagineSalvata {
            get {
                return ResourceManager.GetString("ImmagineSalvata", resourceCulture);
            }
        }
        
        internal static string NotesPlaceholder {
            get {
                return ResourceManager.GetString("NotesPlaceholder", resourceCulture);
            }
        }
        
        internal static string Dummy {
            get {
                return ResourceManager.GetString("Dummy", resourceCulture);
            }
        }
        
        internal static string Informazioni_Temporali_Titolo {
            get {
                return ResourceManager.GetString("Informazioni.Temporali.Titolo", resourceCulture);
            }
        }
        
        internal static string Notifiche_Titolo {
            get {
                return ResourceManager.GetString("Notifiche.Titolo", resourceCulture);
            }
        }
        
        internal static string Notifiche_Testo {
            get {
                return ResourceManager.GetString("Notifiche.Testo", resourceCulture);
            }
        }
        
        internal static string Notifiche_Dettaglio_Testo {
            get {
                return ResourceManager.GetString("Notifiche.Dettaglio.Testo", resourceCulture);
            }
        }
        
        internal static string Notifiche_RilevatoFenomeno {
            get {
                return ResourceManager.GetString("Notifiche.RilevatoFenomeno", resourceCulture);
            }
        }
        
        internal static string Notifiche_ChilometriDalCapoluogo {
            get {
                return ResourceManager.GetString("Notifiche.ChilometriDalCapoluogo", resourceCulture);
            }
        }
        
        internal static string Notifica_Titolo {
            get {
                return ResourceManager.GetString("Notifica.Titolo", resourceCulture);
            }
        }
        
        internal static string Impostazioni_Titolo {
            get {
                return ResourceManager.GetString("Impostazioni.Titolo", resourceCulture);
            }
        }
        
        internal static string Impostazioni_Comuni_Testo {
            get {
                return ResourceManager.GetString("Impostazioni.Comuni.Testo", resourceCulture);
            }
        }
        
        internal static string Impostazioni_Comune_Testo {
            get {
                return ResourceManager.GetString("Impostazioni.Comune.Testo", resourceCulture);
            }
        }
        
        internal static string Impostazioni_RadarFulmini_Testo {
            get {
                return ResourceManager.GetString("Impostazioni.RadarFulmini.Testo", resourceCulture);
            }
        }
        
        internal static string Impostazioni_Mappa_Titolo {
            get {
                return ResourceManager.GetString("Impostazioni.Mappa.Titolo", resourceCulture);
            }
        }
        
        internal static string Impostazioni_RadarFulmini_Titolo {
            get {
                return ResourceManager.GetString("Impostazioni.RadarFulmini.Titolo", resourceCulture);
            }
        }
        
        internal static string Impostazioni_SelezionaLocalita_Titolo {
            get {
                return ResourceManager.GetString("Impostazioni.SelezionaLocalita.Titolo", resourceCulture);
            }
        }
        
        internal static string Impostazioni_CercaComune_Titolo {
            get {
                return ResourceManager.GetString("Impostazioni.CercaComune.Titolo", resourceCulture);
            }
        }
        
        internal static string Impostazioni_Lingua_Titolo {
            get {
                return ResourceManager.GetString("Impostazioni.Lingua.Titolo", resourceCulture);
            }
        }
        
        internal static string Impostazioni_Notifiche_Titolo {
            get {
                return ResourceManager.GetString("Impostazioni.Notifiche.Titolo", resourceCulture);
            }
        }
        
        internal static string Impostazioni_Notifiche_Testo {
            get {
                return ResourceManager.GetString("Impostazioni.Notifiche.Testo", resourceCulture);
            }
        }
        
        internal static string Impostazioni_Notifiche_AbilitaNotifiche {
            get {
                return ResourceManager.GetString("Impostazioni.Notifiche.AbilitaNotifiche", resourceCulture);
            }
        }
        
        internal static string Impostazioni_Notifiche_Intervallo {
            get {
                return ResourceManager.GetString("Impostazioni.Notifiche.Intervallo", resourceCulture);
            }
        }
        
        internal static string Impostazioni_Notifiche_Suono {
            get {
                return ResourceManager.GetString("Impostazioni.Notifiche.Suono", resourceCulture);
            }
        }
        
        internal static string Impostazioni_Notifiche_NonDisturbare {
            get {
                return ResourceManager.GetString("Impostazioni.Notifiche.NonDisturbare", resourceCulture);
            }
        }
        
        internal static string Impostazioni_Notifiche_NonDisturbare_Da {
            get {
                return ResourceManager.GetString("Impostazioni.Notifiche.NonDisturbare.Da", resourceCulture);
            }
        }
        
        internal static string Impostazioni_Notifiche_NonDisturbare_A {
            get {
                return ResourceManager.GetString("Impostazioni.Notifiche.NonDisturbare.A", resourceCulture);
            }
        }
        
        internal static string Informazioni_Titolo {
            get {
                return ResourceManager.GetString("Informazioni.Titolo", resourceCulture);
            }
        }
        
        internal static string Impostazioni_Comune_Intensita {
            get {
                return ResourceManager.GetString("Impostazioni.Comune.Intensita", resourceCulture);
            }
        }
        
        internal static string Impostazioni_Comune_Raggio {
            get {
                return ResourceManager.GetString("Impostazioni.Comune.Raggio", resourceCulture);
            }
        }
        
        internal static string Impostazioni_Comune_MostraRaggio {
            get {
                return ResourceManager.GetString("Impostazioni.Comune.MostraRaggio", resourceCulture);
            }
        }
        
        internal static string Share_Titolo {
            get {
                return ResourceManager.GetString("Share.Titolo", resourceCulture);
            }
        }
        
        internal static string Variables_Overlay_Radar {
            get {
                return ResourceManager.GetString("Variables.Overlay.Radar", resourceCulture);
            }
        }
        
        internal static string Variables_Overlay_Fulmini {
            get {
                return ResourceManager.GetString("Variables.Overlay.Fulmini", resourceCulture);
            }
        }
        
        internal static string Variables_Overlay_Ibrida {
            get {
                return ResourceManager.GetString("Variables.Overlay.Ibrida", resourceCulture);
            }
        }
        
        internal static string Variables_Intensita_Intenso {
            get {
                return ResourceManager.GetString("Variables.Intensita.Intenso", resourceCulture);
            }
        }
        
        internal static string Variables_Intensita_MoltoIntenso {
            get {
                return ResourceManager.GetString("Variables.Intensita.MoltoIntenso", resourceCulture);
            }
        }
        
        internal static string Variables_ora {
            get {
                return ResourceManager.GetString("Variables.ora", resourceCulture);
            }
        }
        
        internal static string Variables_ore {
            get {
                return ResourceManager.GetString("Variables.ore", resourceCulture);
            }
        }
        
        internal static string Variables_minuti {
            get {
                return ResourceManager.GetString("Variables.minuti", resourceCulture);
            }
        }
        
        internal static string Variables_AnimationSpeeds_lenta {
            get {
                return ResourceManager.GetString("Variables.AnimationSpeeds.lenta", resourceCulture);
            }
        }
        
        internal static string Variables_AnimationSpeeds_media {
            get {
                return ResourceManager.GetString("Variables.AnimationSpeeds.media", resourceCulture);
            }
        }
        
        internal static string Variables_AnimationSpeeds_rapida {
            get {
                return ResourceManager.GetString("Variables.AnimationSpeeds.rapida", resourceCulture);
            }
        }
        
        internal static string Variables_Sounds_tuono {
            get {
                return ResourceManager.GetString("Variables.Sounds.tuono", resourceCulture);
            }
        }
        
        internal static string Variables_MapTypes_Standard {
            get {
                return ResourceManager.GetString("Variables.MapTypes.Standard", resourceCulture);
            }
        }
        
        internal static string Variables_MapTypes_Rilievo {
            get {
                return ResourceManager.GetString("Variables.MapTypes.Rilievo", resourceCulture);
            }
        }
        
        internal static string Variables_MapTypes_Satellite {
            get {
                return ResourceManager.GetString("Variables.MapTypes.Satellite", resourceCulture);
            }
        }
        
        internal static string Variables_MapTypes_Ibrida {
            get {
                return ResourceManager.GetString("Variables.MapTypes.Ibrida", resourceCulture);
            }
        }
        
        internal static string MapControl_Annulla {
            get {
                return ResourceManager.GetString("MapControl.Annulla", resourceCulture);
            }
        }
        
        internal static string MapControl_ScegliLayer {
            get {
                return ResourceManager.GetString("MapControl.ScegliLayer", resourceCulture);
            }
        }
    }
}
